# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../motionRecordUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1568, 619)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        MainWindow.setFont(font)
        self.setupTab = QtWidgets.QWidget()
        self.setupTab.setObjectName("setupTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.setupTab)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.setupTab)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.setupTab)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_9.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.setupTab)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.RearLeftShoulderLESet = QtWidgets.QLineEdit(self.setupTab)
        self.RearLeftShoulderLESet.setObjectName("RearLeftShoulderLESet")
        self.verticalLayout_10.addWidget(self.RearLeftShoulderLESet)
        self.RearLeftFemerLESet = QtWidgets.QLineEdit(self.setupTab)
        self.RearLeftFemerLESet.setObjectName("RearLeftFemerLESet")
        self.verticalLayout_10.addWidget(self.RearLeftFemerLESet)
        self.RearLeftLegLESet = QtWidgets.QLineEdit(self.setupTab)
        self.RearLeftLegLESet.setObjectName("RearLeftLegLESet")
        self.verticalLayout_10.addWidget(self.RearLeftLegLESet)
        self.horizontalLayout_6.addLayout(self.verticalLayout_10)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.setupTab)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_11.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(self.setupTab)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        self.label_11 = QtWidgets.QLabel(self.setupTab)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_11.addWidget(self.label_11)
        self.horizontalLayout_7.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.RearRightShoulderLESet = QtWidgets.QLineEdit(self.setupTab)
        self.RearRightShoulderLESet.setObjectName("RearRightShoulderLESet")
        self.verticalLayout_12.addWidget(self.RearRightShoulderLESet)
        self.RearRightFemerLESet = QtWidgets.QLineEdit(self.setupTab)
        self.RearRightFemerLESet.setObjectName("RearRightFemerLESet")
        self.verticalLayout_12.addWidget(self.RearRightFemerLESet)
        self.RearRightLegLESet = QtWidgets.QLineEdit(self.setupTab)
        self.RearRightLegLESet.setObjectName("RearRightLegLESet")
        self.verticalLayout_12.addWidget(self.RearRightLegLESet)
        self.horizontalLayout_7.addLayout(self.verticalLayout_12)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 2, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.fronlabel = QtWidgets.QLabel(self.setupTab)
        self.fronlabel.setObjectName("fronlabel")
        self.verticalLayout_5.addWidget(self.fronlabel)
        self.label_3 = QtWidgets.QLabel(self.setupTab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.setupTab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.FrontLeftShoulderLESet = QtWidgets.QLineEdit(self.setupTab)
        self.FrontLeftShoulderLESet.setInputMask("")
        self.FrontLeftShoulderLESet.setText("")
        self.FrontLeftShoulderLESet.setObjectName("FrontLeftShoulderLESet")
        self.verticalLayout_6.addWidget(self.FrontLeftShoulderLESet)
        self.FrontLeftFemerLESet = QtWidgets.QLineEdit(self.setupTab)
        self.FrontLeftFemerLESet.setObjectName("FrontLeftFemerLESet")
        self.verticalLayout_6.addWidget(self.FrontLeftFemerLESet)
        self.FrontLeftLegLESet = QtWidgets.QLineEdit(self.setupTab)
        self.FrontLeftLegLESet.setObjectName("FrontLeftLegLESet")
        self.verticalLayout_6.addWidget(self.FrontLeftLegLESet)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.setupTab)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.setupTab)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.setupTab)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.FrontRightShoulderLESet = QtWidgets.QLineEdit(self.setupTab)
        self.FrontRightShoulderLESet.setObjectName("FrontRightShoulderLESet")
        self.verticalLayout_8.addWidget(self.FrontRightShoulderLESet)
        self.FrontRightFemerLESet = QtWidgets.QLineEdit(self.setupTab)
        self.FrontRightFemerLESet.setObjectName("FrontRightFemerLESet")
        self.verticalLayout_8.addWidget(self.FrontRightFemerLESet)
        self.FrontRightLegLESet = QtWidgets.QLineEdit(self.setupTab)
        self.FrontRightLegLESet.setObjectName("FrontRightLegLESet")
        self.verticalLayout_8.addWidget(self.FrontRightLegLESet)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.setupTab)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.portLESet = QtWidgets.QLineEdit(self.setupTab)
        self.portLESet.setObjectName("portLESet")
        self.horizontalLayout_8.addWidget(self.portLESet)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.setupTab)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.baudCBSet = QtWidgets.QComboBox(self.setupTab)
        self.baudCBSet.setObjectName("baudCBSet")
        self.horizontalLayout_9.addWidget(self.baudCBSet)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 0, 1, 1, 1)
        self.connectButtonSet = QtWidgets.QPushButton(self.setupTab)
        self.connectButtonSet.setObjectName("connectButtonSet")
        self.gridLayout_2.addWidget(self.connectButtonSet, 3, 0, 1, 1)
        self.emergencyStopButtonSet = QtWidgets.QPushButton(self.setupTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.emergencyStopButtonSet.setFont(font)
        self.emergencyStopButtonSet.setObjectName("emergencyStopButtonSet")
        self.gridLayout_2.addWidget(self.emergencyStopButtonSet, 3, 1, 1, 1)
        self.gridLayout_2.setRowStretch(1, 1)
        self.gridLayout_2.setRowStretch(2, 1)
        MainWindow.addTab(self.setupTab, "")
        self._calibrateServoTab = QtWidgets.QWidget()
        self._calibrateServoTab.setAutoFillBackground(False)
        self._calibrateServoTab.setObjectName("_calibrateServoTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self._calibrateServoTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.calibrateServoButtonCS = QtWidgets.QPushButton(self._calibrateServoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrateServoButtonCS.sizePolicy().hasHeightForWidth())
        self.calibrateServoButtonCS.setSizePolicy(sizePolicy)
        self.calibrateServoButtonCS.setCheckable(True)
        self.calibrateServoButtonCS.setObjectName("calibrateServoButtonCS")
        self.horizontalLayout_3.addWidget(self.calibrateServoButtonCS)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frontLeftShoulderLabelCS = QtWidgets.QLabel(self._calibrateServoTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.frontLeftShoulderLabelCS.setFont(font)
        self.frontLeftShoulderLabelCS.setObjectName("frontLeftShoulderLabelCS")
        self.verticalLayout_4.addWidget(self.frontLeftShoulderLabelCS)
        self.frontLeftFemerLabelCS = QtWidgets.QLabel(self._calibrateServoTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.frontLeftFemerLabelCS.setFont(font)
        self.frontLeftFemerLabelCS.setScaledContents(False)
        self.frontLeftFemerLabelCS.setObjectName("frontLeftFemerLabelCS")
        self.verticalLayout_4.addWidget(self.frontLeftFemerLabelCS)
        self.frontLeftLegLabelCS = QtWidgets.QLabel(self._calibrateServoTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.frontLeftLegLabelCS.setFont(font)
        self.frontLeftLegLabelCS.setObjectName("frontLeftLegLabelCS")
        self.verticalLayout_4.addWidget(self.frontLeftLegLabelCS)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rearLeftShoulderLabelCS = QtWidgets.QLabel(self._calibrateServoTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.rearLeftShoulderLabelCS.setFont(font)
        self.rearLeftShoulderLabelCS.setObjectName("rearLeftShoulderLabelCS")
        self.verticalLayout_3.addWidget(self.rearLeftShoulderLabelCS)
        self.rearLeftFemerLabelCS = QtWidgets.QLabel(self._calibrateServoTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.rearLeftFemerLabelCS.setFont(font)
        self.rearLeftFemerLabelCS.setObjectName("rearLeftFemerLabelCS")
        self.verticalLayout_3.addWidget(self.rearLeftFemerLabelCS)
        self.rearLeftLegLabelCS = QtWidgets.QLabel(self._calibrateServoTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.rearLeftLegLabelCS.setFont(font)
        self.rearLeftLegLabelCS.setObjectName("rearLeftLegLabelCS")
        self.verticalLayout_3.addWidget(self.rearLeftLegLabelCS)
        self.gridLayout.addLayout(self.verticalLayout_3, 3, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rearRightShoulderCS = QtWidgets.QLabel(self._calibrateServoTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.rearRightShoulderCS.setFont(font)
        self.rearRightShoulderCS.setObjectName("rearRightShoulderCS")
        self.verticalLayout.addWidget(self.rearRightShoulderCS)
        self.rearRightFemerLabelCS = QtWidgets.QLabel(self._calibrateServoTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.rearRightFemerLabelCS.setFont(font)
        self.rearRightFemerLabelCS.setObjectName("rearRightFemerLabelCS")
        self.verticalLayout.addWidget(self.rearRightFemerLabelCS)
        self.rearRightLegLabelCS = QtWidgets.QLabel(self._calibrateServoTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.rearRightLegLabelCS.setFont(font)
        self.rearRightLegLabelCS.setObjectName("rearRightLegLabelCS")
        self.verticalLayout.addWidget(self.rearRightLegLabelCS)
        self.gridLayout.addLayout(self.verticalLayout, 3, 3, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frontRightShoulderLabelCS = QtWidgets.QLabel(self._calibrateServoTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.frontRightShoulderLabelCS.setFont(font)
        self.frontRightShoulderLabelCS.setObjectName("frontRightShoulderLabelCS")
        self.verticalLayout_2.addWidget(self.frontRightShoulderLabelCS)
        self.frontRightFemerLabelCS = QtWidgets.QLabel(self._calibrateServoTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.frontRightFemerLabelCS.setFont(font)
        self.frontRightFemerLabelCS.setObjectName("frontRightFemerLabelCS")
        self.verticalLayout_2.addWidget(self.frontRightFemerLabelCS)
        self.frontRightLegLabelCS = QtWidgets.QLabel(self._calibrateServoTab)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.frontRightLegLabelCS.setFont(font)
        self.frontRightLegLabelCS.setObjectName("frontRightLegLabelCS")
        self.verticalLayout_2.addWidget(self.frontRightLegLabelCS)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 3, 1, 1)
        self.stopCalibrationButtonCS = QtWidgets.QPushButton(self._calibrateServoTab)
        self.stopCalibrationButtonCS.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopCalibrationButtonCS.sizePolicy().hasHeightForWidth())
        self.stopCalibrationButtonCS.setSizePolicy(sizePolicy)
        self.stopCalibrationButtonCS.setObjectName("stopCalibrationButtonCS")
        self.gridLayout.addWidget(self.stopCalibrationButtonCS, 4, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 2, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        self.line = QtWidgets.QFrame(self._calibrateServoTab)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self._calibrateServoTab)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(5)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.addTab(self._calibrateServoTab, "")
        self._manualControlTab = QtWidgets.QWidget()
        self._manualControlTab.setObjectName("_manualControlTab")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self._manualControlTab)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_17 = QtWidgets.QLabel(self._manualControlTab)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_16.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self._manualControlTab)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_16.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self._manualControlTab)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_16.addWidget(self.label_19)
        self.horizontalLayout_10.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.rearLeftShoulderSliderMC = QtWidgets.QSlider(self._manualControlTab)
        self.rearLeftShoulderSliderMC.setOrientation(QtCore.Qt.Horizontal)
        self.rearLeftShoulderSliderMC.setObjectName("rearLeftShoulderSliderMC")
        self.verticalLayout_17.addWidget(self.rearLeftShoulderSliderMC)
        self.rearLeftFemerSliderMC = QtWidgets.QSlider(self._manualControlTab)
        self.rearLeftFemerSliderMC.setOrientation(QtCore.Qt.Horizontal)
        self.rearLeftFemerSliderMC.setObjectName("rearLeftFemerSliderMC")
        self.verticalLayout_17.addWidget(self.rearLeftFemerSliderMC)
        self.rearLeftLegSliderMC = QtWidgets.QSlider(self._manualControlTab)
        self.rearLeftLegSliderMC.setOrientation(QtCore.Qt.Horizontal)
        self.rearLeftLegSliderMC.setObjectName("rearLeftLegSliderMC")
        self.verticalLayout_17.addWidget(self.rearLeftLegSliderMC)
        self.horizontalLayout_10.addLayout(self.verticalLayout_17)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.line_3 = QtWidgets.QFrame(self._manualControlTab)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(5)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_11.addWidget(self.line_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_14 = QtWidgets.QLabel(self._manualControlTab)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_13.addWidget(self.label_14)
        self.label_16 = QtWidgets.QLabel(self._manualControlTab)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_13.addWidget(self.label_16)
        self.label_15 = QtWidgets.QLabel(self._manualControlTab)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_13.addWidget(self.label_15)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frontLeftShoulderSliderMC = QtWidgets.QSlider(self._manualControlTab)
        self.frontLeftShoulderSliderMC.setOrientation(QtCore.Qt.Horizontal)
        self.frontLeftShoulderSliderMC.setObjectName("frontLeftShoulderSliderMC")
        self.verticalLayout_14.addWidget(self.frontLeftShoulderSliderMC)
        self.frontLeftFemerSliderMC = QtWidgets.QSlider(self._manualControlTab)
        self.frontLeftFemerSliderMC.setOrientation(QtCore.Qt.Horizontal)
        self.frontLeftFemerSliderMC.setObjectName("frontLeftFemerSliderMC")
        self.verticalLayout_14.addWidget(self.frontLeftFemerSliderMC)
        self.frontLeftLegSliderMC = QtWidgets.QSlider(self._manualControlTab)
        self.frontLeftLegSliderMC.setOrientation(QtCore.Qt.Horizontal)
        self.frontLeftLegSliderMC.setObjectName("frontLeftLegSliderMC")
        self.verticalLayout_14.addWidget(self.frontLeftLegSliderMC)
        self.horizontalLayout_2.addLayout(self.verticalLayout_14)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_2)
        self.verticalLayout_23.addLayout(self.horizontalLayout_11)
        self.line_5 = QtWidgets.QFrame(self._manualControlTab)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(5)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_23.addWidget(self.line_5)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_20 = QtWidgets.QLabel(self._manualControlTab)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_18.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self._manualControlTab)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_18.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self._manualControlTab)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_18.addWidget(self.label_22)
        self.horizontalLayout_13.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.rearRightShoulderSliderMC = QtWidgets.QSlider(self._manualControlTab)
        self.rearRightShoulderSliderMC.setOrientation(QtCore.Qt.Horizontal)
        self.rearRightShoulderSliderMC.setObjectName("rearRightShoulderSliderMC")
        self.verticalLayout_19.addWidget(self.rearRightShoulderSliderMC)
        self.rearRightFemerSliderMC = QtWidgets.QSlider(self._manualControlTab)
        self.rearRightFemerSliderMC.setOrientation(QtCore.Qt.Horizontal)
        self.rearRightFemerSliderMC.setObjectName("rearRightFemerSliderMC")
        self.verticalLayout_19.addWidget(self.rearRightFemerSliderMC)
        self.rearRightLegSliderMC = QtWidgets.QSlider(self._manualControlTab)
        self.rearRightLegSliderMC.setOrientation(QtCore.Qt.Horizontal)
        self.rearRightLegSliderMC.setObjectName("rearRightLegSliderMC")
        self.verticalLayout_19.addWidget(self.rearRightLegSliderMC)
        self.horizontalLayout_13.addLayout(self.verticalLayout_19)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_13)
        self.line_4 = QtWidgets.QFrame(self._manualControlTab)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(5)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_12.addWidget(self.line_4)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_23 = QtWidgets.QLabel(self._manualControlTab)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_20.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self._manualControlTab)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_20.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self._manualControlTab)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_20.addWidget(self.label_25)
        self.horizontalLayout_14.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frontRightShoulderSliderMC = QtWidgets.QSlider(self._manualControlTab)
        self.frontRightShoulderSliderMC.setOrientation(QtCore.Qt.Horizontal)
        self.frontRightShoulderSliderMC.setObjectName("frontRightShoulderSliderMC")
        self.verticalLayout_21.addWidget(self.frontRightShoulderSliderMC)
        self.frontRightFemerSliderMC = QtWidgets.QSlider(self._manualControlTab)
        self.frontRightFemerSliderMC.setOrientation(QtCore.Qt.Horizontal)
        self.frontRightFemerSliderMC.setObjectName("frontRightFemerSliderMC")
        self.verticalLayout_21.addWidget(self.frontRightFemerSliderMC)
        self.frontRightLegSliderMC = QtWidgets.QSlider(self._manualControlTab)
        self.frontRightLegSliderMC.setOrientation(QtCore.Qt.Horizontal)
        self.frontRightLegSliderMC.setObjectName("frontRightLegSliderMC")
        self.verticalLayout_21.addWidget(self.frontRightLegSliderMC)
        self.horizontalLayout_14.addLayout(self.verticalLayout_21)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_14)
        self.verticalLayout_22.addLayout(self.horizontalLayout_12)
        self.verticalLayout_23.addLayout(self.verticalLayout_22)
        self.motorsEnableButtonMC = QtWidgets.QPushButton(self._manualControlTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motorsEnableButtonMC.sizePolicy().hasHeightForWidth())
        self.motorsEnableButtonMC.setSizePolicy(sizePolicy)
        self.motorsEnableButtonMC.setCheckable(True)
        self.motorsEnableButtonMC.setObjectName("motorsEnableButtonMC")
        self.verticalLayout_23.addWidget(self.motorsEnableButtonMC)
        self.verticalLayout_23.setStretch(0, 2)
        self.verticalLayout_23.setStretch(1, 1)
        self.verticalLayout_23.setStretch(2, 2)
        self.verticalLayout_23.setStretch(3, 1)
        MainWindow.addTab(self._manualControlTab, "")
        self._motionRecorderTab = QtWidgets.QWidget()
        self._motionRecorderTab.setEnabled(True)
        self._motionRecorderTab.setObjectName("_motionRecorderTab")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self._motionRecorderTab)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.motionRecordTableMR = QtWidgets.QTableView(self._motionRecorderTab)
        self.motionRecordTableMR.setInputMethodHints(QtCore.Qt.ImhNone)
        self.motionRecordTableMR.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.motionRecordTableMR.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.motionRecordTableMR.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.motionRecordTableMR.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.motionRecordTableMR.setObjectName("motionRecordTableMR")
        self.motionRecordTableMR.horizontalHeader().setCascadingSectionResizes(False)
        self.motionRecordTableMR.horizontalHeader().setDefaultSectionSize(115)
        self.motionRecordTableMR.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_25.addWidget(self.motionRecordTableMR)
        self.manualSlidersLayoutMR = QtWidgets.QHBoxLayout()
        self.manualSlidersLayoutMR.setObjectName("manualSlidersLayoutMR")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.frontLeftShoulderLabelMR = CustomQLabel(self._motionRecorderTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frontLeftShoulderLabelMR.setFont(font)
        self.frontLeftShoulderLabelMR.setAlignment(QtCore.Qt.AlignCenter)
        self.frontLeftShoulderLabelMR.setObjectName("frontLeftShoulderLabelMR")
        self.verticalLayout_27.addWidget(self.frontLeftShoulderLabelMR)
        self.frontLeftShoulderSliderMR = CustomQSlider(self._motionRecorderTab)
        self.frontLeftShoulderSliderMR.setMinimum(0)
        self.frontLeftShoulderSliderMR.setOrientation(QtCore.Qt.Horizontal)
        self.frontLeftShoulderSliderMR.setObjectName("frontLeftShoulderSliderMR")
        self.verticalLayout_27.addWidget(self.frontLeftShoulderSliderMR)
        self.manualSlidersLayoutMR.addLayout(self.verticalLayout_27)
        self.line_14 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.manualSlidersLayoutMR.addWidget(self.line_14)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.frontLeftFemurLabelMR = CustomQLabel(self._motionRecorderTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frontLeftFemurLabelMR.setFont(font)
        self.frontLeftFemurLabelMR.setAlignment(QtCore.Qt.AlignCenter)
        self.frontLeftFemurLabelMR.setObjectName("frontLeftFemurLabelMR")
        self.verticalLayout_28.addWidget(self.frontLeftFemurLabelMR)
        self.frontLeftFemurSliderMR = CustomQSlider(self._motionRecorderTab)
        self.frontLeftFemurSliderMR.setOrientation(QtCore.Qt.Horizontal)
        self.frontLeftFemurSliderMR.setObjectName("frontLeftFemurSliderMR")
        self.verticalLayout_28.addWidget(self.frontLeftFemurSliderMR)
        self.manualSlidersLayoutMR.addLayout(self.verticalLayout_28)
        self.line_13 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.manualSlidersLayoutMR.addWidget(self.line_13)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.frontLeftLegLabelMR = CustomQLabel(self._motionRecorderTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frontLeftLegLabelMR.setFont(font)
        self.frontLeftLegLabelMR.setAlignment(QtCore.Qt.AlignCenter)
        self.frontLeftLegLabelMR.setObjectName("frontLeftLegLabelMR")
        self.verticalLayout_30.addWidget(self.frontLeftLegLabelMR)
        self.frontLeftLegSliderMR = CustomQSlider(self._motionRecorderTab)
        self.frontLeftLegSliderMR.setOrientation(QtCore.Qt.Horizontal)
        self.frontLeftLegSliderMR.setObjectName("frontLeftLegSliderMR")
        self.verticalLayout_30.addWidget(self.frontLeftLegSliderMR)
        self.manualSlidersLayoutMR.addLayout(self.verticalLayout_30)
        self.line_26 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_26.setLineWidth(3)
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setObjectName("line_26")
        self.manualSlidersLayoutMR.addWidget(self.line_26)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.frontRightShoulderLabelMR = CustomQLabel(self._motionRecorderTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frontRightShoulderLabelMR.setFont(font)
        self.frontRightShoulderLabelMR.setAlignment(QtCore.Qt.AlignCenter)
        self.frontRightShoulderLabelMR.setObjectName("frontRightShoulderLabelMR")
        self.verticalLayout_29.addWidget(self.frontRightShoulderLabelMR)
        self.frontRightShoulderSliderMR = CustomQSlider(self._motionRecorderTab)
        self.frontRightShoulderSliderMR.setOrientation(QtCore.Qt.Horizontal)
        self.frontRightShoulderSliderMR.setObjectName("frontRightShoulderSliderMR")
        self.verticalLayout_29.addWidget(self.frontRightShoulderSliderMR)
        self.manualSlidersLayoutMR.addLayout(self.verticalLayout_29)
        self.line_27 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.manualSlidersLayoutMR.addWidget(self.line_27)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.frontRightFemurLabelMR = CustomQLabel(self._motionRecorderTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frontRightFemurLabelMR.setFont(font)
        self.frontRightFemurLabelMR.setAlignment(QtCore.Qt.AlignCenter)
        self.frontRightFemurLabelMR.setObjectName("frontRightFemurLabelMR")
        self.verticalLayout_31.addWidget(self.frontRightFemurLabelMR)
        self.frontRightFemurSliderMR = CustomQSlider(self._motionRecorderTab)
        self.frontRightFemurSliderMR.setOrientation(QtCore.Qt.Horizontal)
        self.frontRightFemurSliderMR.setObjectName("frontRightFemurSliderMR")
        self.verticalLayout_31.addWidget(self.frontRightFemurSliderMR)
        self.manualSlidersLayoutMR.addLayout(self.verticalLayout_31)
        self.line_28 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.manualSlidersLayoutMR.addWidget(self.line_28)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.frontRightLegLabelMR = CustomQLabel(self._motionRecorderTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frontRightLegLabelMR.setFont(font)
        self.frontRightLegLabelMR.setAlignment(QtCore.Qt.AlignCenter)
        self.frontRightLegLabelMR.setObjectName("frontRightLegLabelMR")
        self.verticalLayout_32.addWidget(self.frontRightLegLabelMR)
        self.frontRightLegSliderMR = CustomQSlider(self._motionRecorderTab)
        self.frontRightLegSliderMR.setOrientation(QtCore.Qt.Horizontal)
        self.frontRightLegSliderMR.setObjectName("frontRightLegSliderMR")
        self.verticalLayout_32.addWidget(self.frontRightLegSliderMR)
        self.manualSlidersLayoutMR.addLayout(self.verticalLayout_32)
        self.line_29 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_29.setLineWidth(3)
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setObjectName("line_29")
        self.manualSlidersLayoutMR.addWidget(self.line_29)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.rearLeftShoulderLabelMR = CustomQLabel(self._motionRecorderTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rearLeftShoulderLabelMR.setFont(font)
        self.rearLeftShoulderLabelMR.setAlignment(QtCore.Qt.AlignCenter)
        self.rearLeftShoulderLabelMR.setObjectName("rearLeftShoulderLabelMR")
        self.verticalLayout_34.addWidget(self.rearLeftShoulderLabelMR)
        self.rearLeftShoulderSliderMR = CustomQSlider(self._motionRecorderTab)
        self.rearLeftShoulderSliderMR.setOrientation(QtCore.Qt.Horizontal)
        self.rearLeftShoulderSliderMR.setObjectName("rearLeftShoulderSliderMR")
        self.verticalLayout_34.addWidget(self.rearLeftShoulderSliderMR)
        self.manualSlidersLayoutMR.addLayout(self.verticalLayout_34)
        self.line_30 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_30.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.manualSlidersLayoutMR.addWidget(self.line_30)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.rearLeftFemurLabelMR = CustomQLabel(self._motionRecorderTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rearLeftFemurLabelMR.setFont(font)
        self.rearLeftFemurLabelMR.setAlignment(QtCore.Qt.AlignCenter)
        self.rearLeftFemurLabelMR.setObjectName("rearLeftFemurLabelMR")
        self.verticalLayout_33.addWidget(self.rearLeftFemurLabelMR)
        self.rearLeftFemurSliderMR = CustomQSlider(self._motionRecorderTab)
        self.rearLeftFemurSliderMR.setOrientation(QtCore.Qt.Horizontal)
        self.rearLeftFemurSliderMR.setObjectName("rearLeftFemurSliderMR")
        self.verticalLayout_33.addWidget(self.rearLeftFemurSliderMR)
        self.manualSlidersLayoutMR.addLayout(self.verticalLayout_33)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.rearLeftLegLabelMR = CustomQLabel(self._motionRecorderTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rearLeftLegLabelMR.setFont(font)
        self.rearLeftLegLabelMR.setAlignment(QtCore.Qt.AlignCenter)
        self.rearLeftLegLabelMR.setObjectName("rearLeftLegLabelMR")
        self.verticalLayout_35.addWidget(self.rearLeftLegLabelMR)
        self.rearLeftLegSliderMR = CustomQSlider(self._motionRecorderTab)
        self.rearLeftLegSliderMR.setOrientation(QtCore.Qt.Horizontal)
        self.rearLeftLegSliderMR.setObjectName("rearLeftLegSliderMR")
        self.verticalLayout_35.addWidget(self.rearLeftLegSliderMR)
        self.manualSlidersLayoutMR.addLayout(self.verticalLayout_35)
        self.line_31 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_31.setLineWidth(3)
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setObjectName("line_31")
        self.manualSlidersLayoutMR.addWidget(self.line_31)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.rearRightShoulderLabelMR = CustomQLabel(self._motionRecorderTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rearRightShoulderLabelMR.setFont(font)
        self.rearRightShoulderLabelMR.setAlignment(QtCore.Qt.AlignCenter)
        self.rearRightShoulderLabelMR.setObjectName("rearRightShoulderLabelMR")
        self.verticalLayout_36.addWidget(self.rearRightShoulderLabelMR)
        self.rearRightShoulderSliderMR = CustomQSlider(self._motionRecorderTab)
        self.rearRightShoulderSliderMR.setOrientation(QtCore.Qt.Horizontal)
        self.rearRightShoulderSliderMR.setObjectName("rearRightShoulderSliderMR")
        self.verticalLayout_36.addWidget(self.rearRightShoulderSliderMR)
        self.manualSlidersLayoutMR.addLayout(self.verticalLayout_36)
        self.line_32 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_32.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.manualSlidersLayoutMR.addWidget(self.line_32)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.rearRightFemurLabelMR = CustomQLabel(self._motionRecorderTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rearRightFemurLabelMR.setFont(font)
        self.rearRightFemurLabelMR.setAlignment(QtCore.Qt.AlignCenter)
        self.rearRightFemurLabelMR.setObjectName("rearRightFemurLabelMR")
        self.verticalLayout_37.addWidget(self.rearRightFemurLabelMR)
        self.rearRightFemurSliderMR = CustomQSlider(self._motionRecorderTab)
        self.rearRightFemurSliderMR.setOrientation(QtCore.Qt.Horizontal)
        self.rearRightFemurSliderMR.setObjectName("rearRightFemurSliderMR")
        self.verticalLayout_37.addWidget(self.rearRightFemurSliderMR)
        self.manualSlidersLayoutMR.addLayout(self.verticalLayout_37)
        self.line_25 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.manualSlidersLayoutMR.addWidget(self.line_25)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.rearRightLegLabelMR = CustomQLabel(self._motionRecorderTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rearRightLegLabelMR.setFont(font)
        self.rearRightLegLabelMR.setAlignment(QtCore.Qt.AlignCenter)
        self.rearRightLegLabelMR.setObjectName("rearRightLegLabelMR")
        self.verticalLayout_38.addWidget(self.rearRightLegLabelMR)
        self.rearRightLegSliderMR = CustomQSlider(self._motionRecorderTab)
        self.rearRightLegSliderMR.setOrientation(QtCore.Qt.Horizontal)
        self.rearRightLegSliderMR.setObjectName("rearRightLegSliderMR")
        self.verticalLayout_38.addWidget(self.rearRightLegSliderMR)
        self.manualSlidersLayoutMR.addLayout(self.verticalLayout_38)
        self.line_33 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_33.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.manualSlidersLayoutMR.addWidget(self.line_33)
        self.verticalLayout_25.addLayout(self.manualSlidersLayoutMR)
        self.line_12 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_25.addWidget(self.line_12)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.motionsListViewMR = QtWidgets.QListWidget(self._motionRecorderTab)
        self.motionsListViewMR.setObjectName("motionsListViewMR")
        self.horizontalLayout_16.addWidget(self.motionsListViewMR)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.playMotionButtonMR = QtWidgets.QPushButton(self._motionRecorderTab)
        self.playMotionButtonMR.setCheckable(True)
        self.playMotionButtonMR.setObjectName("playMotionButtonMR")
        self.verticalLayout_24.addWidget(self.playMotionButtonMR)
        self.line_9 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_9.setLineWidth(2)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_24.addWidget(self.line_9)
        self.motionNameLineEditMR = QtWidgets.QLineEdit(self._motionRecorderTab)
        self.motionNameLineEditMR.setObjectName("motionNameLineEditMR")
        self.verticalLayout_24.addWidget(self.motionNameLineEditMR)
        self.saveMotionButtonMR = QtWidgets.QPushButton(self._motionRecorderTab)
        self.saveMotionButtonMR.setObjectName("saveMotionButtonMR")
        self.verticalLayout_24.addWidget(self.saveMotionButtonMR)
        self.loadMotionButtonMR = QtWidgets.QPushButton(self._motionRecorderTab)
        self.loadMotionButtonMR.setObjectName("loadMotionButtonMR")
        self.verticalLayout_24.addWidget(self.loadMotionButtonMR)
        self.appendMotionButton = QtWidgets.QPushButton(self._motionRecorderTab)
        self.appendMotionButton.setObjectName("appendMotionButton")
        self.verticalLayout_24.addWidget(self.appendMotionButton)
        self.line_6 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_24.addWidget(self.line_6)
        self.newMotionButtonMR = QtWidgets.QPushButton(self._motionRecorderTab)
        self.newMotionButtonMR.setObjectName("newMotionButtonMR")
        self.verticalLayout_24.addWidget(self.newMotionButtonMR)
        self.horizontalLayout_16.addLayout(self.verticalLayout_24)
        self.line_7 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_16.addWidget(self.line_7)
        self.enableMotorsButtonMR = QtWidgets.QPushButton(self._motionRecorderTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enableMotorsButtonMR.sizePolicy().hasHeightForWidth())
        self.enableMotorsButtonMR.setSizePolicy(sizePolicy)
        self.enableMotorsButtonMR.setCheckable(True)
        self.enableMotorsButtonMR.setObjectName("enableMotorsButtonMR")
        self.horizontalLayout_16.addWidget(self.enableMotorsButtonMR)
        self.startRecordingMotionButtonMR = QtWidgets.QPushButton(self._motionRecorderTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startRecordingMotionButtonMR.sizePolicy().hasHeightForWidth())
        self.startRecordingMotionButtonMR.setSizePolicy(sizePolicy)
        self.startRecordingMotionButtonMR.setCheckable(True)
        self.startRecordingMotionButtonMR.setObjectName("startRecordingMotionButtonMR")
        self.horizontalLayout_16.addWidget(self.startRecordingMotionButtonMR)
        self.addNewRowButtonMR = QtWidgets.QPushButton(self._motionRecorderTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addNewRowButtonMR.sizePolicy().hasHeightForWidth())
        self.addNewRowButtonMR.setSizePolicy(sizePolicy)
        self.addNewRowButtonMR.setObjectName("addNewRowButtonMR")
        self.horizontalLayout_16.addWidget(self.addNewRowButtonMR)
        self.manualRecordButtonMR = QtWidgets.QPushButton(self._motionRecorderTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manualRecordButtonMR.sizePolicy().hasHeightForWidth())
        self.manualRecordButtonMR.setSizePolicy(sizePolicy)
        self.manualRecordButtonMR.setCheckable(True)
        self.manualRecordButtonMR.setObjectName("manualRecordButtonMR")
        self.horizontalLayout_16.addWidget(self.manualRecordButtonMR)
        self.line_8 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_8.setLineWidth(2)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_16.addWidget(self.line_8)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_26 = QtWidgets.QLabel(self._motionRecorderTab)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_15.addWidget(self.label_26)
        self.line_10 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_15.addWidget(self.line_10)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_27 = QtWidgets.QLabel(self._motionRecorderTab)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_15.addWidget(self.label_27)
        self.secondsSpinMR = QtWidgets.QDoubleSpinBox(self._motionRecorderTab)
        self.secondsSpinMR.setEnabled(False)
        self.secondsSpinMR.setDecimals(3)
        self.secondsSpinMR.setMaximum(60.99)
        self.secondsSpinMR.setSingleStep(0.1)
        self.secondsSpinMR.setObjectName("secondsSpinMR")
        self.horizontalLayout_15.addWidget(self.secondsSpinMR)
        self.verticalLayout_15.addLayout(self.horizontalLayout_15)
        self.line_16 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setObjectName("line_16")
        self.verticalLayout_15.addWidget(self.line_16)
        self.label_28 = QtWidgets.QLabel(self._motionRecorderTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_15.addWidget(self.label_28)
        self.line_15 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_15.addWidget(self.line_15)
        self.torqueSliderMR = QtWidgets.QSlider(self._motionRecorderTab)
        self.torqueSliderMR.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.torqueSliderMR.sizePolicy().hasHeightForWidth())
        self.torqueSliderMR.setSizePolicy(sizePolicy)
        self.torqueSliderMR.setMaximum(1023)
        self.torqueSliderMR.setOrientation(QtCore.Qt.Horizontal)
        self.torqueSliderMR.setObjectName("torqueSliderMR")
        self.verticalLayout_15.addWidget(self.torqueSliderMR)
        self.verticalLayout_15.setStretch(1, 1)
        self.verticalLayout_15.setStretch(2, 2)
        self.horizontalLayout_16.addLayout(self.verticalLayout_15)
        self.line_11 = QtWidgets.QFrame(self._motionRecorderTab)
        self.line_11.setLineWidth(2)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_16.addWidget(self.line_11)
        self.editModeButtonMR = QtWidgets.QPushButton(self._motionRecorderTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editModeButtonMR.sizePolicy().hasHeightForWidth())
        self.editModeButtonMR.setSizePolicy(sizePolicy)
        self.editModeButtonMR.setCheckable(True)
        self.editModeButtonMR.setObjectName("editModeButtonMR")
        self.horizontalLayout_16.addWidget(self.editModeButtonMR)
        self.horizontalLayout_16.setStretch(1, 1)
        self.horizontalLayout_16.setStretch(2, 4)
        self.horizontalLayout_16.setStretch(4, 1)
        self.horizontalLayout_16.setStretch(5, 1)
        self.horizontalLayout_16.setStretch(8, 1)
        self.verticalLayout_25.addLayout(self.horizontalLayout_16)
        self.verticalLayout_25.setStretch(0, 2)
        self.verticalLayout_25.setStretch(3, 1)
        MainWindow.addTab(self._motionRecorderTab, "")

        self.retranslateUi(MainWindow)
        MainWindow.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RoboKitty "))
        self.label_7.setText(_translate("MainWindow", "Rear Left Shoulder"))
        self.label_8.setText(_translate("MainWindow", "Rear Left Femer"))
        self.label_9.setText(_translate("MainWindow", "Rear Left Leg"))
        self.label_10.setText(_translate("MainWindow", "Rear Right Shoulder"))
        self.label_12.setText(_translate("MainWindow", "Rear Right Femer"))
        self.label_11.setText(_translate("MainWindow", "Rear Right Leg"))
        self.fronlabel.setText(_translate("MainWindow", "Front Left Shoulder"))
        self.label_3.setText(_translate("MainWindow", "Front Left Femer"))
        self.label_2.setText(_translate("MainWindow", "Front Left Leg"))
        self.label_6.setText(_translate("MainWindow", "Front Right Shoulder"))
        self.label_5.setText(_translate("MainWindow", "Front Right Femer"))
        self.label_4.setText(_translate("MainWindow", "Front Right Leg"))
        self.label.setText(_translate("MainWindow", "Port"))
        self.label_13.setText(_translate("MainWindow", "Baud Rate"))
        self.connectButtonSet.setText(_translate("MainWindow", "Connect"))
        self.emergencyStopButtonSet.setText(_translate("MainWindow", "Emergency Stop"))
        MainWindow.setTabText(MainWindow.indexOf(self.setupTab), _translate("MainWindow", "Setup"))
        self.calibrateServoButtonCS.setText(_translate("MainWindow", "Calibrate Servo"))
        self.frontLeftShoulderLabelCS.setText(_translate("MainWindow", "Front Left Shoulder: "))
        self.frontLeftFemerLabelCS.setText(_translate("MainWindow", "Front Left Femer:"))
        self.frontLeftLegLabelCS.setText(_translate("MainWindow", "Front Left Leg:"))
        self.rearLeftShoulderLabelCS.setText(_translate("MainWindow", "Rear Left Shoulder:"))
        self.rearLeftFemerLabelCS.setText(_translate("MainWindow", "Rear Left Femer:"))
        self.rearLeftLegLabelCS.setText(_translate("MainWindow", "Rear Left Leg:"))
        self.rearRightShoulderCS.setText(_translate("MainWindow", "Rear Right Shoulder:"))
        self.rearRightFemerLabelCS.setText(_translate("MainWindow", "Rear Right Femer:"))
        self.rearRightLegLabelCS.setText(_translate("MainWindow", "Rear Right Leg:"))
        self.frontRightShoulderLabelCS.setText(_translate("MainWindow", "Front Right Shoulder:"))
        self.frontRightFemerLabelCS.setText(_translate("MainWindow", "Front Right Femer: "))
        self.frontRightLegLabelCS.setText(_translate("MainWindow", "Front Right Leg:"))
        self.stopCalibrationButtonCS.setText(_translate("MainWindow", "Stop Calibration"))
        MainWindow.setTabText(MainWindow.indexOf(self._calibrateServoTab), _translate("MainWindow", "Calibrate Servo"))
        self.label_17.setText(_translate("MainWindow", "Rear Left Shoulder"))
        self.label_18.setText(_translate("MainWindow", "Rear Left Femer"))
        self.label_19.setText(_translate("MainWindow", "Rear Left Leg"))
        self.label_14.setText(_translate("MainWindow", "Front Left Shoulder"))
        self.label_16.setText(_translate("MainWindow", "Front Left Femer"))
        self.label_15.setText(_translate("MainWindow", "Front Left Leg"))
        self.label_20.setText(_translate("MainWindow", "Rear Right Shoulder"))
        self.label_21.setText(_translate("MainWindow", "Rear Right Femer"))
        self.label_22.setText(_translate("MainWindow", "Rear Right Leg"))
        self.label_23.setText(_translate("MainWindow", "Front Right Shoulder"))
        self.label_24.setText(_translate("MainWindow", "Front Right Femer"))
        self.label_25.setText(_translate("MainWindow", "Front Right Leg"))
        self.motorsEnableButtonMC.setText(_translate("MainWindow", "Enable Motors"))
        MainWindow.setTabText(MainWindow.indexOf(self._manualControlTab), _translate("MainWindow", "Manual Control"))
        self.frontLeftShoulderLabelMR.setText(_translate("MainWindow", "Front Left Shoulder"))
        self.frontLeftFemurLabelMR.setText(_translate("MainWindow", "Front Left Femur"))
        self.frontLeftLegLabelMR.setText(_translate("MainWindow", "Front Left Leg"))
        self.frontRightShoulderLabelMR.setText(_translate("MainWindow", "Front Right Shoulder"))
        self.frontRightFemurLabelMR.setText(_translate("MainWindow", "Front Right Femur"))
        self.frontRightLegLabelMR.setText(_translate("MainWindow", "Front Right Leg"))
        self.rearLeftShoulderLabelMR.setText(_translate("MainWindow", "Rear Left Shoulder"))
        self.rearLeftFemurLabelMR.setText(_translate("MainWindow", "Rear Left Femur"))
        self.rearLeftLegLabelMR.setText(_translate("MainWindow", "Rear Left Leg"))
        self.rearRightShoulderLabelMR.setText(_translate("MainWindow", "Rear Right Shoulder"))
        self.rearRightFemurLabelMR.setText(_translate("MainWindow", "Rear Right Femur"))
        self.rearRightLegLabelMR.setText(_translate("MainWindow", "Rear Right Leg"))
        self.playMotionButtonMR.setText(_translate("MainWindow", "Play Motion"))
        self.saveMotionButtonMR.setText(_translate("MainWindow", "Save Motion"))
        self.loadMotionButtonMR.setText(_translate("MainWindow", "Load Motion"))
        self.appendMotionButton.setText(_translate("MainWindow", "Append Motion"))
        self.newMotionButtonMR.setText(_translate("MainWindow", "New Motion"))
        self.enableMotorsButtonMR.setText(_translate("MainWindow", "Enable Motors"))
        self.startRecordingMotionButtonMR.setText(_translate("MainWindow", "Start Recording Motion"))
        self.addNewRowButtonMR.setText(_translate("MainWindow", "Add New Row"))
        self.manualRecordButtonMR.setText(_translate("MainWindow", "Slider Mode"))
        self.label_26.setText(_translate("MainWindow", "Delay"))
        self.label_27.setText(_translate("MainWindow", "Seconds      "))
        self.label_28.setText(_translate("MainWindow", "Torque"))
        self.editModeButtonMR.setText(_translate("MainWindow", "Edit \n"
" Mode"))
        MainWindow.setTabText(MainWindow.indexOf(self._motionRecorderTab), _translate("MainWindow", "Motion Recorder"))

from uiHelper.CustomQLabel import CustomQLabel
from uiHelper.CustomQSlider import CustomQSlider
